export const material_data = [
  {
    name: "Item1",
    inventory_code: "IC00123",
    product_code: "PRC20010",
    location: "QC Warehouse",
    part_no: "20",
    quantity: "10",
    type: "RAW",
    status: "AVAILABLE",
    manufacturer: "FD Manufacturer",
  },
  {
    name: "Item2",
    inventory_code: "IC00124",
    product_code: "PRC20011",
    location: "Cebu Warehouse",
    part_no: "40",
    quantity: "12",
    type: "FINISHED",
    status: "NOT AVAILABLE",
    manufacturer: "11 Manufacturer",
  },
  {
    name: "Item3",
    inventory_code: "IC00125",
    product_code: "PRC20012",
    location: "QC Warehouse",
    part_no: "15",
    quantity: "10",
    type: "RAW",
    status: "AVAILABLE",
    manufacturer: "CC Manufacturer",
  },
];
